In [1]:
import qutip as qt
import numpy as np

In [2]:
psi=np.array([[1],[0]])

In [10]:
I=qt.Qobj(np.array([[1,0], [0,1]]))

In [14]:
psi=qt.basis(2,0)
a=qt.tensor(psi,psi.dag(),I)

In [23]:
U=qt.Qobj(np.array([[1,0], [0,1]]))
gama=qt.basis(2,1)
b=qt.tensor(gama,gama.dag(),U)

In [24]:
a+b

Quantum object: dims = [[2, 1, 2], [1, 2, 2]], shape = (4, 4), type = other
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [37]:
np.arange(4).reshape((2,2))

array([[0, 1],
       [2, 3]])

In [43]:
qt.fock(4)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]