In [1]:
import qutip as qt

In [2]:
qt.about()


QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.3.1
Numpy Version:      1.14.0
Scipy Version:      1.0.0
Cython Version:     0.27.3
Matplotlib Version: 2.1.2
Python Version:     3.6.4
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\ProgramData\Anaconda3\lib\site-packages\qutip
Please cite QuTiP in your publication.
For your convenience a bibtex file can be easily generated using `qutip.cite()`


In [3]:
qt.tensor(qt.basis(2, 0), qt.basis(2, 0))

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [4]:
qt.cnot()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [5]:
qt.snot()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

In [6]:
a=qt.Qobj([[0],[0],[1],[0]])

In [7]:
rr=qt.tensor(qt.cnot(),a)
print(rr)

Quantum object: dims = [[2, 2, 4], [2, 2, 1]], shape = (16, 4), type = other
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [9]:
import numpy as np
cn=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

In [10]:
dd=cn*a

In [11]:
dd

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j]])

In [30]:
orn=np.array([[1/2, 1/2, 1, 0]])

orn.T


array([[0.5],
       [0.5],
       [1. ],
       [0. ]])

In [31]:
kk=cn*orn.T

In [32]:
kk

array([[0.5, 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 1. ],
       [0. , 0. , 0. , 0. ]])

In [35]:
pp=qt.tensor(qt.cnot(),qt.Qobj([[0.5],[0.5],[1],[0]]))
pp

Quantum object: dims = [[2, 2, 4], [2, 2, 1]], shape = (16, 4), type = other
Qobj data =
[[0.5 0.  0.  0. ]
 [0.5 0.  0.  0. ]
 [1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]
 [0.  0.  0.  0.5]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0. ]]