In [3]:
import qutip as qt
import numpy as np

In [4]:
psi=qt.Qobj()
print(psi)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]


In [5]:
a=qt.jmat(5/2.0,'+')
a.shape

(6, 6)

In [6]:
q=qt.destroy(4)
q

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [7]:
import math
h=(1/math.sqrt(2))*np.array([[1,1],[1,-1]])

In [8]:
h

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [10]:
h*h

array([[0.5, 0.5],
       [0.5, 0.5]])