In [1]:
import qutip as qt
import numpy as np


In [2]:
I=qt.Qobj(np.eye(2))

In [13]:
import math
b=(1/math.sqrt(2))*(qt.basis(4,0)+qt.basis(4,3))

In [14]:
c=qt.tensor(I,qt.sigmaz())

In [15]:
b

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [16]:
c

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [21]:
qt.spre(c)*qt.spost(b)

TypeError: Input is not a quantum operator